// NOTE: CODE GENERATED BY AI

// Before
// The Address class does almost nothing and is only used by Person.
class Address {
  constructor(street, city) {
    this.street = street;
    this.city = city;
  }
}

class Person {
  constructor(name, street, city) {
    this.name = name;
    this.address = new Address(street, city);
  }

  getAddress() {
    return `${this.address.street}, ${this.address.city}`;
  }
}

const person = new Person("Allan", "123 Main St", "Springfield");
console.log(person.getAddress()); // 123 Main St, Springfield

// After
// The Address class has been inlined into Person.
class Person {
  constructor(name, street, city) {
    this.name = name;
    this.street = street;
    this.city = city;
  }

  getAddress() {
    return `${this.street}, ${this.city}`;
  }
}

const person2 = new Person("Allan", "123 Main St", "Springfield");
console.log(person.getAddress()); // 123 Main St, Springfield
