// NOTE: EXAMPLE GENERATED BY AI AND MODIFIED BY ME

// Before Refactoring: Dead Code Example
// This function is no longer used anywhere in the codebase
function calculateDiscount(price, discount) {
  return price * (discount / 100);
}

// Unused variable
const unusedVariable = "I am not used";

// Unreachable code in a conditional
function checkStatus(status) {
  if (status === "active") {
    console.log("Status is active");
  } else if (status === "inactive") {
    console.log("Status is inactive");
  } else if (status === "unknown") {
    console.log("Status is unknown");
  } else {
    // This branch is unreachable
    console.log("This will never be executed");
  }
}

checkStatus("active");

// Dead code should be removed to simplify the codebase

// After Refactoring: Removed Dead Code
function checkStatus(status) {
    // NOTE: Not use no else statement by Object Calisthenics here
    if (status === "active") {
        console.log("Status is active");
    } else if (status === "inactive") {
        console.log("Status is inactive");
    } else if (status === "unknown") {
        console.log("Status is unknown");
    }
}

checkStatus("inactive");

// The calculateDiscount function and unused variable have been removed
// The unusedVariable is no longer present
