// NOTE: EXAMPLE GENERATED BY AI

// Before Refactoring: Duplicate Code in Two Methods
class Order {
  calculateTotalWithTax() {
    const subtotal = this.items.reduce((sum, item) => sum + item.price, 0);
    const tax = subtotal * 0.1; // 10% tax
    return subtotal + tax;
  }

  calculateDiscountedTotal() {
    const subtotal = this.items.reduce((sum, item) => sum + item.price, 0);
    const discount = subtotal * 0.2; // 20% discount
    return subtotal - discount;
  }
}

// After Refactoring: Extract Method
class OrderRefactored {
  calculateSubtotal() {
    return this.items.reduce((sum, item) => sum + item.price, 0);
  }

  calculateTotalWithTax() {
    const subtotal = this.calculateSubtotal();
    const tax = subtotal * 0.1; // 10% tax
    return subtotal + tax;
  }

  calculateDiscountedTotal() {
    const subtotal = this.calculateSubtotal();
    const discount = subtotal * 0.2; // 20% discount
    return subtotal - discount;
  }
}

// Before Refactoring: Duplicate Code in Subclasses
class RegularCustomer {
  getDiscountedPrice(price) {
    return price * 0.9; // 10% discount
  }
}

class PremiumCustomer {
  getDiscountedPrice(price) {
    return price * 0.8; // 20% discount
  }
}

// After Refactoring: Duplicate Code in Subclasses - Pull Up Method
class Customer {
  getDiscountedPrice(price, discountRate) {
    return price * discountRate;
  }
}

class RegularCustomerRefactored extends Customer {
  getDiscountedPrice(price) {
    return super.getDiscountedPrice(price, 0.9); // 10% discount
  }
}

class PremiumCustomerRefactored extends Customer {
  getDiscountedPrice(price) {
    return super.getDiscountedPrice(price, 0.8); // 20% discount
  }
}

// Before Refactoring: Duplicate Conditional Fragments
// Note: Will not apply no use else from Object Calisthenics here
function processOrder(order) {
  if (order.isExpress) {
    console.log("Processing express order...");
    console.log("Order ID:", order.id);
  } else {
    console.log("Processing standard order...");
    console.log("Order ID:", order.id);
  }
}

// After Refactoring: Consolidate Duplicate Conditional Fragments
// Note: Will not apply no use else from Object Calisthenics here
function processOrderRefactored(order) {
  if (order.isExpress) {
    console.log("Processing express order...");
  } else {
    console.log("Processing standard order...");
  }
  console.log("Order ID:", order.id);
}
